### ISSUE TITLE
Image mix

### ISSUE THREAD

**Issue by kimdg1105** [Bletcher-Project/bletcher_mix#1]
## Description
 Back server에서 온 2개의 url을 열어, mix 작업 후 합성 이미지를 생성합니다.

## Branch
feature/mix

## Progress
- [x] 이미지 url 두 개 받기
- [x] 확장자 처리
- [x] 이미지 합성 후 클라우디나리 저장
- [x] 합성 이미지 이름, 타입, url 백 서버로 전송

**Comment by yoongoing** [comment]
저희 url로 http요청이라 png이미지 업로드 및 합성 시 정상작동 합니다.
별다른 처리가 필요하지 않을것 같습니다.
